#!/bin/bash

echo 'Installing pre-requisites...'
DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y -q --no-install-recommends \
    aptitude \
    libedit-dev \
    libxml2-dev \
    libsqlite3-dev \
    uuid-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

JANSSON_VER=2.12
echo "...installing jansson"                                   
    wget -O - http://www.digip.org/jansson/releases/jansson-${JANSSON_VER}.tar.gz | zcat | tar -xf -
    cd jansson-${JANSSON_VER}                                           
    ./configure                                                         
    make all install 
